# Generated by Django 4.2 on 2023-05-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=11, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=130, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Tu Numero')),
                ('direccion', models.CharField(max_length=100)),
                ('fec_nac', models.DateField()),
                ('vivienda', models.IntegerField(choices=[(1, 'Casa con patio grande'), (2, 'Casa con patio pequeño'), (3, 'Casa sin patio'), (4, 'Departamento')])),
            ],
        ),
    ]
